# Generated by Django 4.2.11 on 2024-03-23 13:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profiles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255),
        ),
    ]
