# Generated by Django 4.2.11 on 2024-03-23 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profiles_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
